# Generated by Django 6.0.1 on 2026-01-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme_template',
            field=models.CharField(choices=[('mariage_floral', 'Mariage Floral'), ('mariage_gold', 'Mariage Doré Luxury'), ('conf_tech', 'Conférence Tech (Dark)'), ('conf_minimal', 'Conférence Minimaliste'), ('anniv_fun', 'Anniversaire Coloré')], default='mariage_floral', max_length=50),
        ),
    ]
