# Generated by Django 6.0.1 on 2026-01-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_event_cover_image_alter_event_theme_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
