# Generated by Django 6.0.1 on 2026-01-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_guest_checked_in_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guestbook_message',
            field=models.TextField(blank=True, help_text="Message pour le livre d'or"),
        ),
        migrations.AddField(
            model_name='guest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DrinkOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_options', to='invitation.event')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='selected_drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitation.drinkoption'),
        ),
    ]
