# Generated by Django 6.0.1 on 2026-01-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_guest_guestbook_message_guest_responded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='theme_template',
            field=models.CharField(choices=[('mariage_floral', 'Mariage Floral'), ('mariage_gold', 'Mariage Doré Luxury'), ('conf_tech', 'Conférence Tech (Dark)'), ('conf_minimal', 'Conférence Minimaliste'), ('anniv_fun', 'Anniversaire Coloré'), ('mariage_passion', 'Mariage Passion'), ('mariage_pastel_hearts', 'Mariage Pastel')], default='mariage_floral', max_length=50),
        ),
    ]
