# Generated by Django 6.0.1 on 2026-01-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_alter_event_theme_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='has_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
